name: Run CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  ci-build:
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    strategy:
      matrix:
        include:
          - php-version: 7.3
            shared-test-version: 4.x-dev
          - php-version: 7.4
            shared-test-version: 4.x-dev
          - php-version: 8.0
            shared-test-version: 5.x-dev
          - php-version: 8.1
            shared-test-version: dev-main
          - php-version: 8.2
            shared-test-version: dev-main


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: ./.github/actions/ci
        with:
          php-version: ${{ matrix.php-version }}
          shared-test-version: ${{ matrix.shared-test-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
